services:
    front:
        container_name: toxicity_analyzer_front
        build: ./front
        image: toxicity-analyzer-front:latest
        ports:
            - "3000:3000"
            - "4040:4040"
    back:
        container_name: toxicity_analyzer_back
        build: ./back
        image: toxicity-analyzer-back:latest
        ports:
            - "5000:5000"
            - "8011:8010"
    model:
        container_name: toxicity_analyzer_model
        build: ./model
        image: toxicity-analyzer-model:latest
        ports:
            - "7000:8000"
            - "8010:8010"
    node_exporter:
        image: prom/node-exporter
        container_name: node-exporter
        ports:
            - 9100:9100
        pid: host
        restart: always
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        ports:
            - 9090:9090
        volumes:
            - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./monitoring/rules.yml:/etc/prometheus/rules.yml
        restart: always
    alertmanager:
        image: prom/alertmanager
        container_name: alertmanager
        ports:
            - 9093:9093
        volumes:
            - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
        command:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
            - "--storage.path=/alertmanager"
        restart: always
    discord-alertmanager:
        image: benjojo/alertmanager-discord
        container_name: discord-alertmanager
        environment:
            - DISCORD_WEBHOOK=https://discord.com/api/webhooks/944527309950574622/GhZnru_5m0sm67y2-bsYV1OFAFuQltNwArEj4THygSnLK-HMC9KSjRKG40UxHthJXtfh
        restart: always
    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
            - 4000:3000
        environment:
            - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
        restart: always
    cadvisor:
        image: gcr.io/cadvisor/cadvisor
        ports:
            - 4041:8080
        container_name: cadvisor
        restart: always